### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by vizthex123** [jimmyjon711/FactorioExtended-Plus-Power#6]
I've found that whenever I load up the game, this error appears: https://imgur.com/zJn4qk0

If I disable this mod it works though.

**Comment by jimmyjon711** [comment]
Well I think the real issue here is that AiXMatter mod has their big electric poles replacement group as electric-poles which is the same for medium poles. I have different replacement group for medium poles(electric-pole) and big electric poles(big-electric-pole). 

If they were the same group then the big-electric-poles would replace the medium poles.

**Comment by AlienXAXS** [comment]
Hi,
This has been fixed in the latest version of AiX Matter - thanks for the detailed description of the problem @jimmyjon711 and ty @vizthex123 for submitting a report.
